# Generated by Django 4.0.3 on 2022-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=40)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
